# Generated by Django 5.0.6 on 2024-07-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app2', '0002_capital_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
