# Generated by Django 5.0.6 on 2024-07-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 8, 16, 19, 27, 240433, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
